# Yarn configuration for CI/Vercel

# Use classic node_modules linker on Vercel to avoid PnP issues
nodeLinker: node-modules

# Vercel sets immutable installs in CI; disable to allow lockfile updates during build
enableImmutableInstalls: false

# Optional: reduce noise
checksumBehavior: update

yarnPath: .yarn/releases/yarn-4.9.2.cjs
